CMakeLists.txt

Makes it easier to import to Eclipse CDT as well

Rename project to reflect actual subproject name

---

opencog/util/exceptions.cc

Some exception messages can contain the symbols %s %d %x %u etc and these can be interpreted as string formatting commands.  This in turn can lead to unexpected crashes. 
This happens in practice with guile exceptions, which can contains strings such as "%start-stack"  Note the %s in there...

Fix crazy format crash

---

README.md

Add dependencies(libboost and optional doxygen) to README

---

opencog/util/Logger.cc
opencog/util/Logger.h
scripts/util/log_per_component.sh
tests/util/LoggerUTest.cxxtest

Address issue #34.
I don't merge just yet as it needs more real world testing first... Soon.

Logger support component

---

opencog/util/Counter.h
opencog/util/Cover_Tree.h
opencog/util/Logger.cc
opencog/util/Logger.h
opencog/util/RandGen.h
opencog/util/StringManipulator.cc
opencog/util/StringManipulator.h
opencog/util/StringTokenizer.cc
opencog/util/StringTokenizer.h
opencog/util/exceptions.cc
opencog/util/exceptions.h
opencog/util/files.cc
opencog/util/files.h
opencog/util/iostreamContainer.h
opencog/util/jaccard_index.h
opencog/util/log_prog_name.h
opencog/util/mt19937ar.cc
opencog/util/mt19937ar.h
opencog/util/octime.cc
opencog/util/octime.h
opencog/util/random.h
tests/util/LoggerUTest.cxxtest
tests/util/StringTokenizerUTest.cxxtest
tests/util/iostreamContainerUTest.cxxtest
tests/util/randomUTest.cxxtest

Convert cogutils to follow http://wiki.opencog.org/w/Development_standards#Multi-word_identifiers
If I don't hear from anybody within the next 48h I'll merge (and the corresponding ones on the other repos).

Multi word std

---

opencog/util/Logger.cc

This should not affect any existing code.

Avoid a possible bug.

---

opencog/util/Config.cc
opencog/util/Config.h
opencog/util/Logger.cc
tests/util/ConfigUTest.cxxtest

This should avoid the crash-madness of bug opencog/opencog#2329

Allow users to specify default config parameters.

---

opencog/util/Config.cc
opencog/util/Config.h

I can't figure out what the heck is going on with the opencog config files. Try to add enough functions that it can be debugged.

Config file handling updates

---

opencog/util/Logger.cc

Part two of the previous pull request. I merged too soon.

Actually print the paths that were searched

---

opencog/util/Config.cc
opencog/util/Config.h
opencog/util/Logger.cc
opencog/util/Logger.h

Its impossible to debug the config files, if they are not correctly logged.  This continues with the attempt to fix this problem.

Ongoing attempts to solve the config-file craziness.

---

opencog/util/exceptions.h

Needed for repair work for opencog/atomspace/issues/910

Add a TypeCheckException

---

opencog/util/exceptions.cc
opencog/util/exceptions.h

This will be needed for an upcoming atomspace change...

Add yet another exception type.

---

opencog/util/boost_ext/accumulators/statistics/geometric_mean_mirror.h

Fix issue https://github.com/opencog/moses/issues/44

Fix ‘pow’ is not a member of ‘std’

---

opencog/util/async_method_caller.h

... want a better idea of the system loads.

Add some performance monitoring for the writeback queues

---

opencog/util/numeric.h

Sorry for more snake case I-don't-give-a-fuck thing. Since the cogutils is almost completely consistent in that respect I couldn't resist the urge to perfect it.

Fix remaining snake case

---

opencog/util/CMakeLists.txt
opencog/util/StringManipulator.cc
opencog/util/StringManipulator.h

Revert "Remove StringManipulator"

---

opencog/util/algorithm.h

Should hopefully fix https://github.com/opencog/moses/issues/51

Move set_insertion to be defined when hitting set_union

---

CMakeLists.txt
LICENSE
README.md
circle.yml

Rename to cogutil

---

opencog/util/algorithm.h

alternat container clear function that deallocates memory

Add clear_by_swap

---

opencog/util/mt19937ar.cc
opencog/util/mt19937ar.h

To use it correctly from multiple threads.
See discussion in https://github.com/opencog/atomspace/pull/1656

Make RandGen instance thread local

---

opencog/util/Logger.cc
opencog/util/Logger.h
tests/util/LoggerUTest.cxxtest

Extracting part of https://github.com/opencog/cogutil/pull/108

Add thread id logging for multhreading use cases

---

tests/util/LoggerUTest.cxxtest

For a bug related to multiple logger writing on the same file.

Add utest logger

---

cmake/OpenCogFunctions.cmake

Needed to resolve opencog/atomspace#1834
Note, we have a duplicate of `cmake/OpenCogFunctions.cmake` in the opencog/opencog repo. I haven't updated that one, and I think we should probably delete it to avoid confusion.

Copy scm files to build directory instead of symlinking

---

opencog/util/CMakeLists.txt

revert linking to zlib

---

cmake/OpenCogFunctions.cmake

The test added will be run by ctest

Add cmake macro for adding guile tests 

---

opencog/util/Counter.h
tests/util/CounterUTest.cxxtest

Added boost::arithmetic1/2 and allowed passing of a comparator to the underlying map
Added test for all the new functionality

Counter Improvements

---

cmake/FindGuile.cmake

Version 3.0 includes a JIT compiled to gnu lightning bytecode. Claims to be 4x faster. I will measure shortly.

Add support for guile version 3.0

---

CMakeLists.txt

Re-order the file so that proceeds in a more orderly fashion.
Remove obsolete junk.

General CMakefile cleanup

---

tests/util/CounterUTest.cxxtest

It was a mixture of spaces and tabs, so turn everything into smart tabs.

Fix indentation of CounterUTest

---

opencog/util/Counter.h
tests/util/CounterUTest.cxxtest

Take into account zeros, i.e. values that are in one but not in the
other counter.

Fix Counter::operator*=(const Counter&)

---

opencog/util/exceptions.cc
opencog/util/exceptions.h

It was dereferenceing null pointers and other garbage!

Fix the exception API

---

opencog/util/backtrace-symbols.c

Fast fix for issue https://github.com/opencog/atomspace/issues/2127

Wrap libbfd calls by mutex as libbfd is not thread safe

---

cmake/OpenCogGccOptions.cmake

C++14 is five years ago.  Seems like a reasonable time-frame.

Bump minimum C++ version to c++14 from c++11

---

.circleci/config.yml

Otherwise it checks out the master not the current branch!

Use circleci checkout comment instead of git clone

---

CMakeLists.txt
cmake/FindParallelSTL.cmake
opencog/util/oc_omp.h

Clang doesn't have `parallel/algorithm` yet.

detect parallelism as clang lacks it

---

opencog/util/algorithm.h
tests/util/algorithmUTest.cxxtest

This file was a mixture of space and tabs, make everything tabs.

Fix indentation in alogrithm.h

---

opencog/util/Logger.cc

close logfile after pushing.
This should have gone out with the previous pull req.

Close after flushing

---

opencog/util/concurrent_queue.h
opencog/util/concurrent_stack.h

... now that no one uses them any more.

Remove the signature-conflicted methods

---

opencog/util/Logger.h

failed to remove failed logger fix.

Remove leftover cruft from #206 debugging

---

cmake/OpenCogGccOptions.cmake

There does not seem to any porting required, tested repos (cogutil, atomspace and ure) compile and pass unit tests on my machine.

Move to C++17 (and set minimum gcc version to 6.0)

---

.clang-format
opencog/util/backtrace-symbols.c

Backwards compat for binutils

---

tests/util/zipfUTest.cxxtest

Tighten and expand the unit tests.

All new zipf unit tests

---

opencog/util/zipf.h
tests/util/zipfUTest.cxxtest

Port code from srfi-194 to c++ and expand the unit tests.

Zipf distribution: implement non-zero q

---

opencog/util/Logger.cc

This appears to fix issue opencog/cogserver#34
This bug has been around forever...

Do not touch log-writerss during shutdown.

---

.circleci/config.yml

According to
https://github.com/opencog/asmoses/commit/3d84c524de32a7e241347abd4e7a2e990256ca11

Try to fix build break via asmoses dependency.

---

cmake/OpenCogGccOptions.cmake

Bug #239 - minumum compiler version is 7.0

---

opencog/util/Logger.cc

This should simplify debugging.

Set thread name on logger thread

---

opencog/util/Logger.cc
tests/util/zipfUTest.cxxtest

Suppress compiler warnings on 32-bit systems

---

opencog/util/platform.cc

Mild changes to the platform.cc file, for readability.

Additional platform porting cleanup.

---

opencog/util/exceptions.cc
opencog/util/exceptions.h

Cleanup crufty exception handling code

---

opencog/util/CMakeLists.txt

See https://cmake.org/cmake/help/latest/policy/CMP0115.html
for details.

Silence CMake Policy CMP0115 warnings

---

opencog/util/tree.cc

Cleanup `tree.cc` code, in anticipation of a fix for #267

Tree cleanup

---

opencog/util/lru_cache.h

All sorts of deep template bugs manifest in moses. 
Switching to std:: makes them go away.
Sort of. It seems to improve things ...

Fix moses compile errors by removing boost

---

opencog/util/algorithm.h

Cleanup algorithm.h
