- opencog/util/exceptions.h
- opencog/util/macros.h
I had build problem similar to #2 using gcc 4.6. This fix should help, though I have not checked other instalations.
jacek@ubuntu-js ~/github/cogutils/build $ (master) make
[  5%] Building CXX object opencog/util/CMakeFiles/cogutil.dir/Config.cc.o
In file included from /home/jacek/github/cogutils/opencog/util/Config.cc:50:0:
/home/jacek/github/cogutils/opencog/util/exceptions.h:76:13: error: looser throw specifier for ‘virtual opencog::StandardException::~StandardException()’
/usr/include/c++/4.6/exception:65:13: error:   overriding ‘virtual std::exception::~exception() throw ()’
/home/jacek/github/cogutils/opencog/util/exceptions.h:77:25: error: looser throw specifier for ‘virtual const char* opencog::StandardException::what() const’
/usr/include/c++/4.6/exception:69:25: error: …
> Fixed build problem #2 for GCC 4.6

- opencog/util/RandGen.h
- opencog/util/mt19937ar.cc
- opencog/util/mt19937ar.h
- tests/util/randomUTest.cxxtest
There's this bit of comment that says
```
-/** @todo Once C++11 is fully supported by GCC feel free to remove anything
- * wrapped by #ifndef USE_STL_RANDOM  
- * The situation is confusing... According to gnu.org, this has been
- * supported since gcc-4.3 (but possibly in the tr1 namespace ??)
- * In Ubuntu oneiric, with gcc-4.6.2, the build failed.
- *  With gcc-4.6.3, things work.  I'm confused. This
- * needs more user reports.
- */
```
so I assume removing all the old non-STL random is always wanted.
> Remove non-STL random and added randDiscrete

- opencog/util/RandGen.h
- opencog/util/mt19937ar.cc
- opencog/util/mt19937ar.h
Since the random generator fully relies on STL I decided to have RandGen directly inherits std::mt19937. That way one can use the generator returned by the singleton randGen() in STL distributions.
I would have preferred to have MT19937RandGen inherit std::mt19937 rather than randGen() but I couldn't because RandGen is the abstract generator class used all over in OpenCog, and as far as I can tell there is no abstract STL generator one could use for that.
The next step would be to get rid of RandGen and MT19937RandGen, only keep rangGen() that would return an std::mt19937 generator (or any STL generator), but that involves changing the all callers. Maybe that's not worth it. The most important is that we can now use STL distributions.
> Randgen inherit stl random generator

- opencog/util/CMakeLists.txt
The other option, that I know of, is to refactor all dependent project's preprocessor declarations. That maybe the 'right' thing to do, I don't know, or revert the project name change.
> use include/opencog/util as install path

- opencog/util/Logger.h
- tests/util/LoggerUTest.cxxtest
Fix for issue #20 
The usage is simple
```c++
LAZY_LOG_DEBUG << foo();
```
If the debug level is below DEBUG then foo() is not executed, unlike
```c++
logger().debug() << foo();
```
I choose to keep the LAZY prefix in the macro to help the user to understand the difference between logger().debug() and LAZY_LOG_DEBUG.
> Lazy logger

- README.md
Quick google search provided link to GNU biutils. 
Not sure if it is the same library as intended.
> Updated broken URL link of GNU biutils

- opencog/util/files.cc
assuming that user has compiled opencog under a directory called build.
Hack/fix for issue #47
> Add hack to run the cogserver from scripts/run_cogserver.sh

- opencog/util/files.cc
- opencog/util/files.h
I also removed the hardwired path with build. I don't know if that's ultimately the right thing to do to address #47 but I didn't like the fact that run_cogserver.sh can't deal with build dir with different names than `build`, and whatnot.
> Read OPENCOG_MODULE_PATHS env var for user defined module paths

- opencog/util/functional.h
The error message was
````
/usr/local/include/opencog/util/functional.h:41:6: error: ‘vector’ in namespace ‘std’ does not name a template type
````
> Fix gcc-6 build error

- opencog/util/async_method_caller.h
This is needed for https://github.com/opencog/atomspace/pull/861 and will be accompanied by a pull request that updates the AtomSpace to work with this change.
> Changed async_caller to call const method

- opencog/util/random.h
That way rand_element can be used with boost::ptr_vector
> Replace output type by auto in rand_element

- opencog/util/random.h
This happens to revert 7882ed4, but I think it's better without the trailing as it doesn't add any more genericity that directly putting it in the output type in place of auto.
> Add generalized rand_element for any distribution

- opencog/util/CMakeLists.txt
- opencog/util/sigslot.h
Boost::signals2 are incredibly slow, and account for 5% or 10% of the total atomspace performance. This is a step to try to remedy that icky situation.
> Initial prototype of a fast signal function

- opencog/util/algorithm.h
That way we can write
```c++
is_in(el, set)
```
instead of
```c++
set.find(el) != set.end()
```
> Add is_in convenience function

- scripts/util/time.sh
Script that takes a log file and return the difference in hour:min:sec between the timestamps of the first and last logs. This is convenient to estimate the runtime of some process. Will not work if the time if greater than 24h!
> Measure runtime script given a log file

- opencog/util/CMakeLists.txt
- opencog/util/async_buffer.h
- opencog/util/async_method_caller.h
- opencog/util/concurrent_set.h
The concurrent set allows multiple threads to safely, concurrently add and remove items from an std::set class. Because an std::set can only ever hold one copy of an item, this provides a basic thread-safe de-duplication service.
The write-buffer implements an asynchronous de-duplicated write-back set. Just like the async method caller, it will call a method on a class asynchronously, in a different thread. Unlike the async caller, this will avoid calling the method more than once for the same block of data.  Thus, its useful for implementing a buffer that avoids un-needed (duplicated) operations, such as writes. 
This buffer is used by the SQL backend to avoid storing values that have not been changed since the last store request.
> Add a write buffer, and a concurrent set.

- opencog/util/numeric.h
MOSES build with newer(?) G++ fails (see moses PR #49).  Changing abs() to fabs() fixes this.
> Build fix: changed std::abs() -> std::fabs() to be built with G++ 7.1.0

- opencog/util/algorithm.h
Actual fix for https://github.com/opencog/opencog/issues/2889
Linas fix where creating ambiguity (just like the previously), kinda dangerous cause you wouldn't know whether the compiler would choose the version that modifies the input or the version that doesn't. I renamed it so that no ambiguity is possible.
> Rename set union inplace to set_insertion

- opencog/util/algorithm.h
These are not really range versions, but it's still convenient. I'm
sure eventually this will go into boost, meanwhile this can be used.
> Add "range" versions of any_of, all_of and none_of

- opencog/util/Counter.h
- opencog/util/tree.h
for instance
```
tree<T>(root, {tree<T>(child-1, {grandchild-1, grandchild-2}), child-2})
```
builds
```
root
/  \
child-1  child-2
/    \
grandchild-1 grandchild-2
```
> Add more constructors to allow to compactly build trees

- opencog/util/Logger.cc
```
.../cogutil/opencog/util/Logger.cc:422:60: warning: format '%ld' expects argument of type 'long int', but argument 5 has type '__darwin_suseconds_t {aka int}' [-Wformat]
"[%s:%03ld] ",timestamp, stv.tv_usec / 1000);
~~~~~~~~~~~~~~~~~~^
```
Added explicit cast to long to ensure proper processing.
> type warning fix on OSX

- opencog/util/async_method_caller.h
This pattern exists in opencog/util/async_method_caller.h code twice: 
```
while (...); 
{
... not a loop due to ; above
}
```
Probably not what was intended.  This patch fixes this problem. 
( Passes unit test on Ubuntu 16.04 ; no impact on atomspace tests )
> fix: while loop spinning on ; rather than subsequent loop

- opencog/util/backtrace-symbols.c
#85 is fixed.
Actually I noticed this fault when Opencog test failed in debug on my Ubuntu.
> #85 - segmentation fault in debug mode on attempt to log stack trace

- opencog/util/CMakeLists.txt
- opencog/util/empty_string.h
This is meants to be used when calling oc_to_string in gdb as a work
around for gdb bug with C++11 ABI and overload resolution.
> Add empty_string const static

- cmake/AddCxxtest.cmake
This is to be used for defining cxxtest tests that will require configuration before running.
> Define ADD_CONFIGURABLE_CXXTEST cmake macro

- cmake/CMakeLists.txt
Moving cmake files to ${LIB_INSTALL_DIR}/cmake/CogUtil for consistency with atomspace and opencog. See issue #126
> move cmake files to lib/cmake/CogUtil (fix for #126)

- opencog/util/Logger.cc
- opencog/util/Logger.h
- tests/util/LoggerUTest.cxxtest
Allow the use of multiple loggers, with one message queue per filename.
This is intended to fix issues discussed in #127
> Single-queue message writing

- opencog/util/Counter.h
@ngeiswei So I tried using the RetabIndent from the plugin you recommend but the result is the same. It converts 4 spaces into 1 tab which means as long as you display 1 tab as 4 spaces everything is still aligned correctly.
But since GitHub shows the first tab as 6 spaces long and all others as 8 spaces long this, of course, breaks the alignment. Which shows nicely why I prefer spaces.
Anyway, I fixed the misaligned end of line comment by moving it into its own line.
> White space fix

- opencog/util/numeric.h
Multiple issues with the code. The build break was due to a missing `static inline` declaration.  The compiler warning was due to the C++ spec explicitly calling out this behavior as "undefined".  C++20 fixes this, but C++20 is not generally available, yet.
> Fix build break, compiler warning, formatting. 

- opencog/util/Cover_Tree.h
- opencog/util/KLD.h
- opencog/util/MannWhitneyU.h
- opencog/util/RandGen.h
- opencog/util/algorithm.h
- opencog/util/cluster.h
- opencog/util/comprehension.h
- opencog/util/digraph.h
- opencog/util/files.h
- opencog/util/hashing.h
- opencog/util/iostreamContainer.h
- opencog/util/jaccard_index.h
- opencog/util/lazy_selector.cc
- opencog/util/lazy_selector.h
- opencog/util/log_prog_name.cc
- opencog/util/log_prog_name.h
- opencog/util/macros.h
- opencog/util/numeric.h
- opencog/util/oc_omp.cc
- opencog/util/oc_omp.h
- opencog/util/platform.cc
- opencog/util/random.h
- opencog/util/ranking.h
- opencog/util/sigslot.h
- opencog/util/tbb.h
- opencog/util/tree.cc
- opencog/util/tree.h
- tests/util/numericUTest.cxxtest
numeric.h contained a lot of cruft that is now available directly from standard C++
Also: optimize several slow routines for performance.
Also: remove trailing whitespace in all *.h *.cc files
> Major cleanup to numeric.h

- opencog/util/numeric.h
The compare is hardly "approximate", it effectively demands equality.
> Remove one more mis-named function

- opencog/util/Logger.cc
Otherwise the logger can randomly be initialized to output to stdout
> Initialize LogWriter::printToStdout to false

- CMakeLists.txt
- cmake/CMakeLists.txt
- cmake/OpenCogGccOptions.cmake
Add cmake include file which contains GCC options to be included in root CMakeLists.txt in other opencog repositories. Content of OpenCogGccOptions.cmake is copied from atomspace repo, see https://github.com/opencog/atomspace/blob/387588a33868accddf192bf4f051e8f54872184d/CMakeLists.txt#L51-L121
> Add GCC options include file for cmake

- opencog/util/comprehension.h
- tests/util/comprehensionUTest.cxxtest
C++ vector list and set comprehension is back!!! I had partially disable it due to a gcc bug and the bug has been fixed since then.
> Fix set comprehension

- .circleci/config.yml
Make build jobs less for moses to avoid "c++: internal compiler error: Killed (program cc1plus)" message
> Make build jobs less for moses

- cmake/Summary.cmake
I'm on Android using Termux, atm, where this path doesn't exist.
> Normalize check for /etc/os-release for other distributions that lack it

- opencog/util/numeric.h
Using only `int64_t` in this check lets it work properly on platforms with differing sizes for `long int` or `long long int`.  As of C++11, `std::abs` has overloads that will pick the proper implementation.
> Use platform-independent float ulp type

- tests/util/LoggerUTest.cxxtest
Clang assumes `char == -1` is always false, so this change to respect the `fgetc` function signature better allows the loop to complete and the test to pass on my system.
> clang-compatible fgetc return type

- tests/util/LoggerUTest.cxxtest
Required for test to pass when `/tmp` is not writable.
> respect TMPDIR in LoggerUTest

- CMakeLists.txt
- cmake/FindGNUBacktrace.cmake
- opencog/util/Logger.cc
- opencog/util/backtrace-symbols.h
Aids building on other platforms than just apple and cygwin, that lack this.
> Add specific check for unix backtrace

- opencog/util/Logger.cc
- opencog/util/Logger.h
- tests/util/LoggerUTest.cxxtest
So that each logger can set this flag independently of the other
loggers, regardless of whether they share the same log file.
Fix for issue https://github.com/opencog/cogutil/issues/195
> Move printToStdout out of the log writer

- opencog/util/Logger.cc
- opencog/util/Logger.h
- opencog/util/async_buffer.h
- opencog/util/concurrent_queue.h
- opencog/util/concurrent_set.h
- opencog/util/concurrent_stack.h
Tighten up logger usage, per logger malfunction in issue opencog/atomspace#2371
To be clear: when processes are run in rapid succession, each process opening the same log file, writing to it, and then deleting it, then exiting, there are several nasty issues: 
1) the file delete might not be complete before the next file-open starts, resulting in duplicated content in the log file (I'm assuming that the duplicated content is from the earlier log-file writes.)
2) If the log file is not deleted, it can still happen that writing might not be completed when the process exits, resulting in lost output.
Between 1&2 above, log files can have duplicated content and also be incomplete.  Thoroughly crazy-making for debug.
> Logger safety precautions

- opencog/util/async_method_caller.h
The problem with pop() is that there's a C++ method overloading
clash; the signatures have different return values.
> Use value_pop() instead of pop().

- CMakeLists.txt
- README.md
Attempting to debug the cogserver ShellUTest crash ... I suspect it's boost badness...
> There's no need to check for unused packages.

- opencog/util/pool.h
The resource is copied, it has thus no reason not to be passed by
const.
> Pass const ref in pool::give_back

- .clang-format
- opencog/util/backtrace-symbols.c
This is one of the three opened pull requests opened among OpenCog projects that changes and fixes a few scripts such that you can build and use OpenCog on the new LTS Ubuntu 20.04, coming out this April.
Unfortunately, there is a small fix that I had to apply to Cogutil, so these changes **are not** backwards-compatible.
What changed here is that a few procedures (namely `bfd_get_section_vma`, `bfd_get_section_flags` and `bfd_section_size`) changed their names and/or signature.
Sorry for the reformatting, I couldn't get clang-format to output the same style.
Again, this is not backwards-compatible so I'm just leaving this here in case some day you want to move to 20.04 so perhaps this will save you time.
> Ubuntu 20.04 binutils API fix

- opencog/util/concurrent_queue.h
- opencog/util/concurrent_set.h
- opencog/util/concurrent_stack.h
Unlike the pop() variants, this is capable of returning an empty set.
Therefore, it does not need to throw.
> If queue is closed, then grab everything in queue.

- cmake/OpenCogFindPython.cmake
This is a fix for opencog/atomspace#2643
> Cython 0.24 or later for @property to work with python2

- CMakeLists.txt
- opencog/util/algorithm.h
Explicitly use `boost::placeholders` in order to compile under boost 1.75. Alternatively I could have silenced the error, but this will likely be mandatory at some point so better do it right now. It requires to upgrade boost requirement to boost 1.60, which is 5 year old, so I think it is more than acceptable.
> Fix boost compile error

- opencog/util/CMakeLists.txt
- opencog/util/backtrace-symbols.c
Fixes #236 for me, on Ubuntu 20.04. I didn't check for older versions but now the checks are more exhaustive. I took this idea from another project I found where they had a similar issue and ported it to CMake.
> Fix for Binutils API problems

- .circleci/config.yml
Ideally we should not need that but for some reason escaping my
understanding we do.
> We need to install asmoses before running the unit tests

- opencog/util/platform.h
I beleive these are unused anywhere in opencog. Just remove them.
I think that half the other portability wrappers are also unused;
that needs to be a later commit.
> Remove unused functions.

- cmake/FindGuile.cmake
I have a `libguile.h` under `/usr/include`, which belongs to 1.8.8 version of guile. In this case, `NO_DEFAULT_PATH` needs to be set for it to find the correct header file under `/usr/include/guile/3.0`.
> Fix guile finder

- opencog/util/backtrace-symbols.c
Hopefully, this won't break other users ...!?
> Debian testing does not define PTR type.

- opencog/util/lazy_selector.cc
Message was
/usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders.
> Fix boost warning message.

- opencog/util/misc.h
It has been removed, and generates warning messages.
> std::unary_function is deprecated in c++17

- .circleci/config.yml
MOSES is no longer maintained, and it is experiencing unit test errors. Easiest solution is to stop testing it.
> Stop testing moses.

- .circleci/config.yml
- CMakeLists.txt
After this, it should be safe to to kill CMP00037 testing
> Get ready to remove CMake CMP00037 backwards compat

- etc/CMakeLists.txt
Currently, the installation of ld.so.conf file related to cogutil occurs in /etc. This is not only not portable, as mentionned in the cmake file where this is defined, but moreover requires root privileges. The current PR allows to use -DCMAKE_CONF_PREFIX=/home/mini-me/.config to ensure that this file is deployed locally in somewhere else than /etc. This behaviour is not standard, and these files are not picked up by default. A bit of shell scripting can however make that happen and allow to installation of cogutils to work in userspace without root privileges.
Some script like that in a shell initialisation should do the trick:
```bash
if [[ -d ~/.config/ld.so.conf.d ]]; then
for conf in ~/.config/ld.so.conf.d/*.conf; do
export LD_LIBRARY_PATH=$(cat "$conf" | tr '\n' ':')$LD_LIBRARY_PATH …
```
> Parametrising location of ld.so.conf files.
